export * from "./whatsappMessage.interface";
export * from "./whatsappTextTemplate";
export * from './noVariable';
export * from './noVariableImage'
export * from './oneVariable'
export * from './noVariableImage'
export * from './twoVariable'
export * from './twoVariableImage'
export * from './threeVariables'
export * from './threeVariableImage'
export * from './fourVariables'
export * from './fourVariableImage'
export * from './getPhonesResponse'